### ISSUE TITLE
data problems

### ISSUE THREAD

**Issue by satra** [myyoda/ohbm2018-training#6]
@mih - the following set of steps results in feat not running when i shell into the container

```
$ cd glm_analysis
$ # get the BIDS raw dataset (no actual content)
$ datalad install -d . -s ../bids inputs/rawdata
[INFO   ] Cloning ../bids to '/tmp/test/glm_analysis/inputs/rawdata' 
install(ok): inputs/rawdata (dataset)                                                                                                                                        
action summary:
  add (notneeded: 2, ok: 1)
  install (ok: 1)
  save (ok: 1)
$ tail inputs/rawdata/sub-02/func/sub-02_task-oneback_run-01_bold.json 
tail: cannot open ‘inputs/rawdata/sub-02/func/sub-02_task-oneback_run-01_bold.json’ for reading: No such file or directory
```

is there some magic in `containers-run` that gets the data? i always end up with feat not running on our cluster. i can't run `containers-run` on our cluster because of the security issue here:  https://github.com/datalad/datalad-container/issues/43

**Comment by mih** [comment]
You should be able to `datalad get inputs/rawdata/sub-02/func/sub-02_task-oneback_run-01_bold.json`. If you give `run --input <this file>` it will invoke that for you. `containers-run` merely passes `--input` to `run`.

**Comment by satra** [comment]
thanks @mih - i ended up doing a recursive get for the inputs/rawdata directory, but still running into an undecipherable feat error!

**Comment by satra** [comment]
undecipherable error came from missing package `file`

**Comment by mih** [comment]
Ah! Right, so you were not using the singularity image. That one has it.
